// app/layout.js
// アプリ全体を包むルートレイアウト。全ページ共通の <html> / <body> 構造を定義する

// Google Fonts から Geist ファミリーを next/font 経由で最適化ロードする
import { Geist, Geist_Mono } from "next/font/google";
// アプリ全体に適用するグローバル CSS を読み込む
import "./globals.css";

// サンセリフ体。CSS 変数 --font-geist-sans に割り当て
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// 等幅体。CSS 変数 --font-geist-mono に割り当て
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// サイト全体のデフォルトメタデータ（各ページで上書き可能）
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// children には各ページの内容が渡される
export default function RootLayout({ children }) {
  return (
    // フォント用 CSS 変数をクラスとして付与し、全体に反映させる
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
